name: portfolio-andrija-design

services:
  frontend:
    build:
      context: . # Points to the client directory
      dockerfile: ./client/Dockerfile.prod.client # Dockerfile for the production client (React + Nginx)
    ports:
      - "80:80" # Expose port 80 for HTTP
      - "443:443" # Expose port 443 for HTTPS
    volumes:
      - /etc/letsencrypt/live/portfolio.andrijadesign.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/portfolio.andrijadesign.com/privkey.pem:/etc/nginx/ssl/privkey.pem
    networks:
      - app-network
    env_file: # Load environment variables for the client from the client .env file
      - ./client/.env
    restart: always # Ensure the frontend restarts automatically

  backend:
    build:
      context: . # Points to the server directory
      dockerfile: ./server/Dockerfile.prod.server # Dockerfile for the production server (Node.js)
    ports:
      - "3000:3000" # Expose port 3000 for the backend
    networks:
      - app-network
    env_file: # Load environment variables for the backend from the server .env file
      - ./server/.env
    environment:
      - NODE_ENV=production # Set environment to production
    restart: always # Ensure the backend restarts automatically
    depends_on:
      - frontend # Optional, ensures backend waits for frontend to be up

networks:
  app-network:
    driver: bridge
