services:
  nginx:
    depends_on:
      client:
        condition: service_healthy
      api:
        condition: service_healthy
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3200:80"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:80"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - ./server/.env.development
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
