const images = {
  aceLoungeChair1: "/portfolio-assets/Ace-Lounge-Chair-1.jpg",
  aceLoungeChair2: "/portfolio-assets/Ace-Lounge-Chair-2.jpg",
  aceLoungeChair3: "/portfolio-assets/Ace-Lounge-Chair-3.jpg",
  aceLoungeChair4: "/portfolio-assets/Ace-Lounge-Chair-4.jpg",
  aktjorLine1: "/portfolio-assets/aktjor-line-1.jpg",
  aktjorLine2: "/portfolio-assets/aktjor-line-2.jpg",
  aktjorLine3: "/portfolio-assets/aktjor-line-3.jpg",
  aktjorLine4: "/portfolio-assets/aktjor-line-4.jpg",
  aktjorLine5: "/portfolio-assets/aktjor-line-5.jpg",
  aktjorLine6: "/portfolio-assets/aktjor-line-6.jpg",
  aktjorLine7: "/portfolio-assets/aktjor-line-7.jpg",
  aktjorLine8: "/portfolio-assets/aktjor-line-8.jpg",
  aktjorLine9: "/portfolio-assets/aktjor-line-9.jpg",
  amorphousStool1: "/portfolio-assets/Amorphous-Stool-1.jpg",
  amorphousStool2: "/portfolio-assets/Amorphous-Stool-2.jpg",
  amorphousStool3: "/portfolio-assets/Amorphous-Stool-3.jpg",
  amorphousStool4: "/portfolio-assets/Amorphous-Stool-4.jpg",
  amorphousStool5: "/portfolio-assets/Amorphous-Stool-5.jpg",
  anabeyArmchairGif: "/portfolio-assets/Anabey Armchair (1).gif",
  anabeyArmchairJpg1: "/portfolio-assets/Anabey Armchair (1).jpg",
  anabeyArmchairPng1: "/portfolio-assets/Anabey Armchair (1).png",
  anabeyArmchairPng2: "/portfolio-assets/Anabey Armchair (2).png",
  anabeyArmchairJpg5: "/portfolio-assets/Anabey Armchair (5).jpg",
  anabeyArmchairJpg6: "/portfolio-assets/Anabey Armchair (6).jpg",
  anabeyArmchairJpg7: "/portfolio-assets/Anabey Armchair (7).jpg",
  anabeySofa1: "/portfolio-assets/Anabey Sofa (1).jpg",
  anabeySofa2: "/portfolio-assets/Anabey Sofa (2).jpg",
  anabeySofa3: "/portfolio-assets/Anabey Sofa (3).jpg",
  apparel1: "/portfolio-assets/apparel-1.jpg",
  apparel2: "/portfolio-assets/apparel-2.jpg",
  apparel3: "/portfolio-assets/apparel-3.jpg",
  apparel4: "/portfolio-assets/apparel-4.jpg",
  apparel5: "/portfolio-assets/apparel-5.jpg",
  ashBucket1: "/portfolio-assets/ash bucket (1).jpg",
  ashBucket2: "/portfolio-assets/ash bucket (2).jpg",
  ashBucket3: "/portfolio-assets/ash bucket (3).jpg",
  ashBucket4: "/portfolio-assets/ash bucket (4).jpg",
  ashBucket5: "/portfolio-assets/ash bucket (5).jpg",
  ashBucket6: "/portfolio-assets/ash bucket (6).jpg",
  atlantisBed1: "/portfolio-assets/Atlantis Bed (1).jpg",
  atlantisBed2: "/portfolio-assets/Atlantis Bed (2).jpg",
  atlantisBed3: "/portfolio-assets/Atlantis Bed (3).png",
  atlantisBed4: "/portfolio-assets/Atlantis Bed (4).png",
  bootTray1: "/portfolio-assets/boot-tray (1).jpg",
  bootTray2: "/portfolio-assets/boot-tray (2).jpg",
  bootTray3: "/portfolio-assets/boot-tray (3).jpg",
  bootTray4: "/portfolio-assets/boot-tray (4).jpg",
  bootTray5: "/portfolio-assets/boot-tray (5).jpg",
  bootTray6: "/portfolio-assets/boot-tray (6).jpg",
  bowedWindow1: "/portfolio-assets/bowed-window (1).jpg",
  bowedWindow2: "/portfolio-assets/bowed-window (2).jpg",
  bowedWindow3: "/portfolio-assets/bowed-window (3).jpg",
  calvinArmchair1: "/portfolio-assets/calvin-armchair (1).jpg",
  calvinArmchair2: "/portfolio-assets/calvin-armchair (2).jpg",
  calvinArmchair3: "/portfolio-assets/calvin-armchair (3).jpg",
  calvinArmchair4: "/portfolio-assets/calvin-armchair (4).jpg",
  calvinArmchair5: "/portfolio-assets/calvin-armchair (5).jpg",
  calvinArmchair6: "/portfolio-assets/calvin-armchair (6).jpg",
  carafe1: "/portfolio-assets/Carafe-1.jpg",
  carafe2: "/portfolio-assets/Carafe-2.jpg",
  carafe3: "/portfolio-assets/Carafe-3.jpg",
  carafe4: "/portfolio-assets/Carafe-4.jpg",
  carafe5: "/portfolio-assets/Carafe-5.jpg",
  carafe6: "/portfolio-assets/Carafe-6.jpg",
  carafe7: "/portfolio-assets/Carafe-7.jpg",
  cardCabinet1: "/portfolio-assets/Card-Cabinet-1.jpg",
  cardCabinet2: "/portfolio-assets/Card-Cabinet-2.jpg",
  cardCabinet3: "/portfolio-assets/Card-Cabinet-3.jpg",
  cardCabinet4: "/portfolio-assets/Card-Cabinet-4.jpg",
  cardCabinet5: "/portfolio-assets/Card-Cabinet-5.jpg",
  cardCabinet6: "/portfolio-assets/Card-Cabinet-6.jpg",
  cardCabinet7: "/portfolio-assets/Card-Cabinet-7.jpg",
  cardCabinet8: "/portfolio-assets/Card-Cabinet-8.jpg",
  coatRack1: "/portfolio-assets/Coat Rack (1).jpg",
  coatRack2: "/portfolio-assets/Coat Rack (2).jpg",
  coatRack3: "/portfolio-assets/Coat Rack (3).jpg",
  coatRack4: "/portfolio-assets/Coat Rack (4).jpg",
  coatRack5: "/portfolio-assets/Coat Rack (5).jpg",
  emilySofa1: "/portfolio-assets/Emily Sofa (1).png",
  emilySofa2: "/portfolio-assets/Emily Sofa (2).png",
  emilySofa3: "/portfolio-assets/Emily Sofa (3).png",
  emilySofa4: "/portfolio-assets/Emily Sofa (4).png",
  entranceDoor1: "/portfolio-assets/Entrance Door (1).jpg",
  entranceDoor2: "/portfolio-assets/Entrance Door (2).jpg",
  entranceDoor3: "/portfolio-assets/Entrance Door (3).jpg",
  entranceDoor4: "/portfolio-assets/Entrance Door (4).jpg",
  entranceDoor5: "/portfolio-assets/Entrance Door (5).jpg",
  frontDoor1: "/portfolio-assets/Front-Door (1).jpg",
  frontDoor2: "/portfolio-assets/Front-Door (2).jpg",
  frontDoor3: "/portfolio-assets/Front-Door (3).jpg",
  frontDoor4: "/portfolio-assets/Front-Door (4).jpg",
  frontDoor5: "/portfolio-assets/Front-Door (5).jpg",
  frontDoor6: "/portfolio-assets/Front-Door (6).jpg",
  frontDoor7: "/portfolio-assets/Front-Door (7).jpg",
  frontDoor8: "/portfolio-assets/Front-Door (8).jpg",
  husk1: "/portfolio-assets/Husk (1).jpg",
  husk2: "/portfolio-assets/Husk (2).jpg",
  husk3: "/portfolio-assets/Husk (3).jpg",
  husk4: "/portfolio-assets/Husk (4).jpg",
  husk5: "/portfolio-assets/Husk (5).jpg",
  impressive1: "/portfolio-assets/Impressive (1).jpg",
  impressive2: "/portfolio-assets/Impressive (2).jpg",
  impressive3: "/portfolio-assets/Impressive (3).jpg",
  impressive4: "/portfolio-assets/Impressive (4).jpg",
  impressive5: "/portfolio-assets/Impressive (5).jpg",
  impressive6: "/portfolio-assets/Impressive (6).jpg",
  massager1: "/portfolio-assets/Massager (1).jpg",
  massager2: "/portfolio-assets/Massager (2).jpg",
  massager3: "/portfolio-assets/Massager (3).jpg",
  massager4: "/portfolio-assets/Massager (4).jpg",
  massager5: "/portfolio-assets/Massager (5).jpg",
  mikahChair1: "/portfolio-assets/Mikah-Chair (1).jpg",
  mikahChair2: "/portfolio-assets/Mikah-Chair (2).jpg",
  paperHolder1: "/portfolio-assets/Paper-Holder-1.jpg",
  paperHolder2: "/portfolio-assets/Paper-Holder-2.jpg",
  paperHolder3: "/portfolio-assets/Paper-Holder-3.jpg",
  paperHolder4: "/portfolio-assets/Paper-Holder-4.jpg",
  paperHolder5: "/portfolio-assets/Paper-Holder-5.jpg",
  paperHolder6: "/portfolio-assets/Paper-Holder-6.jpg",
  paperHolder7: "/portfolio-assets/Paper-Holder-7.jpg",
  paperHolder8: "/portfolio-assets/Paper-Holder-8.jpg",
  rockingChair1: "/portfolio-assets/Rocking Chair (1).jpg",
  rockingChair2: "/portfolio-assets/Rocking Chair (2).jpg",
  rockingChair3: "/portfolio-assets/Rocking Chair (3).jpg",
  rockingChair4: "/portfolio-assets/Rocking Chair (4).jpg",
  rockingChair5: "/portfolio-assets/Rocking Chair (5).jpg",
  rockingChair6: "/portfolio-assets/Rocking Chair (6).jpg",
  rockingChair7: "/portfolio-assets/Rocking Chair (7).jpg",
  rockingChair8: "/portfolio-assets/Rocking Chair (8).jpg",
  rockingChair9: "/portfolio-assets/Rocking Chair (9).jpg",
  rumqui1: "/portfolio-assets/Rumqui (1).jpg",
  rumqui2: "/portfolio-assets/Rumqui (2).jpg",
  rumqui3: "/portfolio-assets/Rumqui (3).jpg",
  rumqui4: "/portfolio-assets/Rumqui (4).jpg",
  sawdustMachine1: "/portfolio-assets/Sawdust-Machine-1.jpg",
  sawdustMachine2: "/portfolio-assets/Sawdust-Machine-2.jpg",
  sawdustMachine3: "/portfolio-assets/Sawdust-Machine-3.jpg",
  sawdustMachine4: "/portfolio-assets/Sawdust-Machine-4.jpg",
  showcase1: "/portfolio-assets/Showcase-(1).jpg",
  showcase2: "/portfolio-assets/Showcase-(2).jpg",
  showcase3: "/portfolio-assets/Showcase-(3).jpg",
  sofaCutaway1: "/portfolio-assets/Sofa-Cutaway-1.jpg",
  sofaCutaway2: "/portfolio-assets/Sofa-Cutaway-2.jpg",
  sofaCutaway3: "/portfolio-assets/Sofa-Cutaway-3.jpg",
  sofaCutaway4: "/portfolio-assets/Sofa-Cutaway-4.jpg",
  sofaCutaway5: "/portfolio-assets/Sofa-Cutaway-5.jpg",
  sofaCutaway6: "/portfolio-assets/Sofa-Cutaway-6.jpg",
  soffette1: "/portfolio-assets/soffette (1).jpg",
  soffette2: "/portfolio-assets/soffette (2).jpg",
  soffette3: "/portfolio-assets/soffette (3).jpg",
  soffette4: "/portfolio-assets/soffette (4).jpg",
  soffette5: "/portfolio-assets/soffette (5).jpg",
  vitaChair1: "/portfolio-assets/Vita-Chair-1.jpg",
  vitaChair2: "/portfolio-assets/Vita-Chair-2.jpg",
  vitaChair3: "/portfolio-assets/Vita-Chair-3.jpg",
  waterBottle1: "/portfolio-assets/Water-Bottle-1.jpg",
  waterBottle2: "/portfolio-assets/Water-Bottle-2.jpg",
  waterBottle3: "/portfolio-assets/Water-Bottle-3.jpg",
  waterBottle4: "/portfolio-assets/Water-Bottle-4.jpg",
  waterBottle5: "/portfolio-assets/Water-Bottle-5.jpg",
  waterBottle6: "/portfolio-assets/Water-Bottle-6.jpg"
};

export default images;
