name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-client:latest
          build-args: |
            NODE_ENV=production
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-client:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-client:buildcache,mode=max

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest
          build-args: |
            NODE_ENV=production
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-api:buildcache,mode=max

      - name: Copy docker-compose file to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yaml"
          target: "/var/www/portfolio"
          strip_components: 0
          debug: true
          overwrite: true

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            echo "Checking connection..."

            cd /var/www/portfolio

            # Load production environment variables
            set -a
            source .env
            set +a

            # Pull the latest client and API images
            docker compose -f docker-compose.prod.yaml pull

            # Stop existing containers
            docker compose -f docker-compose.prod.yaml down --remove-orphans

            # Start new containers
            docker compose -f docker-compose.prod.yaml up -d

            # Clean up old images
            docker image prune -f

            # Verify deployment
            docker compose -f docker-compose.prod.yaml ps
