name: Deploy to VPS

on:
  push:
    branches:
      - master # Change to your branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -R ${{ secrets.VPS_IP }} || true

      - name: Add updated VPS host key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          scp -r ./* root@${{ secrets.VPS_IP }}:/var/www/portfolio-andrija-design

      - name: SSH Commands
        run: |
          ssh -v root@${{ secrets.VPS_IP }} << 'EOF'
          cd /var/www/portfolio-andrija-design
          docker-compose down
          docker-compose up --build -d
          EOF
