name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install and build client
      - name: Install dependencies and build client
        working-directory: ./client
        run: |
          npm cache clean --force
          rm -rf node_modules
          npm install
          npm run build
      # Debugging: Check client dist folder
      - name: Check client dist folder before deploy
        working-directory: ./client
        run: ls -la ./dist/

      # Debugging: Echo GitHub Workspace
      - name: Echo GitHub Workspace path
        run: echo "GitHub Workspace is ${GITHUB_WORKSPACE}"

      # Install and build server
      - name: Install server dependencies and build server
        working-directory: ./server
        run: |
          npm cache clean --force
          rm -rf node_modules
          npm install
          npm run build
      # Debugging: Check server dist folder
      - name: Check server dist folder before deploy
        working-directory: ./server
        run: ls -la ./dist/

      # Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /var/www/portfolio-andrija-design/client
            mkdir -p /var/www/portfolio-andrija-design/server

            # Copy files to the VPS
            rsync -avz --delete ${GITHUB_WORKSPACE}/client/dist/ /var/www/portfolio-andrija-design/client/
            rsync -avz --delete ${GITHUB_WORKSPACE}/server/dist/ /var/www/portfolio-andrija-design/server/

            # Navigate to server directory
            cd /var/www/portfolio-andrija-design/server

            # Install server dependencies in production mode
            NODE_ENV=production npm install

            # Restart the server using PM2
            pm2 stop portfolio-andrija-design || true
            pm2 start dist/index.js --name portfolio-andrija-design
