name: Deploy to VPS

on:
  push:
    branches:
      - master # Change to your branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          mkdir -p ~/.ssh
          echo "88.223.92.155 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbcjq3AXEP9UJhagnreawnklBquW6toI/w3ugYQKyIgQenU8X5eQrP2hDLUaJ85kJxTfBrWRT66SKK6SvhCI9ZzdaDIccx1vAonFc0zA1cIK/I9kvxQZavKlJ4hmw90OSV0UyN5E14LCP0HbMgVrrUVgaUmnZn81sVMwqVYYulzDsOfIB35VGih0pZtAemKn0dX21GVVPaUyxYbJ84ErXfKnw4kU2FowBtNZA4lSf4ZCXtUwbuNZMXsC9kajW0yfe9GduX+XCdUaJPs+FUKqeSJspC5qzEAQdqZJU26mDjBVfdfg3O9OhM9WDrIxjBEAJ9XnKS/9h5XJ1nBsHBUL3pMH5a12rkZWgTKkdF6Aj9GfsplhgIRKQxfobJGXj3YGdB8plQGu7I4mQueFapDWn//im6KometP/sUAQwif/egPhEvx6R5qVHast3CQyuaT7mYQusKYrNfdYGyT5xJC2tsu8ebTlcOjwSDhU+mgzUF2ixthnF6NB2PG/JaJ9vvIU=" >> ~/.ssh/known_hosts
          echo "88.223.92.155 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAq5znc5b3L2On3/Ka8bS3TVlNBGlqc0RseTuNTg/ACAOt7Vxlc/TPOv/f7IQhWGU1KB2KF9Z6ZCvG5pVu5X3MA=" >> ~/.ssh/known_hosts
          echo "88.223.92.155 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRKGskYQTVd0Cb0ex33UBbLwMvaVT2bPZDuKFh1UiSD" >> ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          scp -r ./* root@${{ secrets.VPS_IP }}:/var/www/portfolio-andrija-design

      - name: SSH Commands
        run: |
          ssh root@${{ secrets.VPS_IP }} << 'EOF'
          cd /var/www/portfolio-andrija-design
          docker-compose down
          docker-compose up --build -d
          EOF
