name: Deploy to VPS

on:
  push:
    branches:
      - master # Change to your branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_IP }} ssh-rsa ${{ secrets.SSH_RSA_KEY }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.VPS_IP }} ecdsa-sha2-nistp256 ${{ secrets.SSH_ECDSA_KEY }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.VPS_IP }} ssh-ed25519 ${{ secrets.SSH_ED25519_KEY }}" >> ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          scp -r ./* root@${{ secrets.VPS_IP }}:/var/www/portfolio-andrija-design

      - name: SSH Commands
        run: |
          ssh -v root@${{ secrets.VPS_IP }} << 'EOF'
          cd /var/www/portfolio-andrija-design
          docker-compose down
          docker-compose up --build -d
          EOF
